import { dehydrate, QueryClient } from '@tanstack/react-query'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getMarketsTicker } from '~/api/upbit/marketsTicker'
import { getMarketSymbols } from '~/api/upbit/marketSymbols'
import Button from '~/components/button/Button'
import MarketCard from '~/components/molecules/marketCard/MarketCard'
import VerticalCarousel from '~/components/organism/verticalCarousel/VerticalCarousel'
import { useAppSelector } from '~/features/hooks'
import { wrapper } from '~/features/store'
import { invoke } from '~/features/upblit/market/symbolSlice'
import { useMartetsTicker } from '~/hooks/queries/useMartetsTicker'
import styles from '~/styles/Home.module.scss'

const Home: NextPage = () => {
 const marketsSymbol = useAppSelector((state) =>
  state.marketSymbol.symbol
   .slice(0, 10)
   .map(({ market }) => market)
   .join(','),
 )
 const { data, refetch } = useMartetsTicker(marketsSymbol)

 return (
  <div className={styles.container}>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <main className={styles.main}>
    <Button onClick={() => refetch()}>sdf </Button>
    <div
     style={{
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      width: '100%',
      height: '110px',
      margin: '0 auto',
      background: '#ededed',
      borderRadius: '1rem',
     }}
    >
     <VerticalCarousel offsetRadius={4}>
      {data?.map((data) => (
       <MarketCard
        key={data.market}
        logo={`https://static.upbit.com/logos/${data.market.split('-')[1]}.png`}
        marketSymbol={data.market}
       />
      ))}
     </VerticalCarousel>
    </div>
    <h1 className={styles.title}>
     Welcome to <a href="https://nextjs.org">Next.js!</a>
    </h1>

    <p className={styles.description}>
     Get started by editing <code className={styles.code}>pages/index.tsx</code>
    </p>

    <div className={styles.grid}>
     <a href="https://nextjs.org/docs" className={styles.card}>
      <h2>Documentation &rarr;</h2>
      <p>Find in-depth information about Next.js features and API.</p>
     </a>

     <a href="https://nextjs.org/learn" className={styles.card}>
      <h2>Learn &rarr;</h2>
      <p>Learn about Next.js in an interactive course with quizzes!</p>
     </a>

     <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
      <h2>Examples &rarr;</h2>
      <p>Discover and deploy boilerplate example Next.js projects.</p>
     </a>

     <a
      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      className={styles.card}
     >
      <h2>Deploy &rarr;</h2>
      <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
     </a>
    </div>
   </main>

   <footer className={styles.footer}>
    <a
     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
     target="_blank"
     rel="noopener noreferrer"
    >
     Powered by{' '}
     <span className={styles.logo}>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
     </span>
    </a>
   </footer>
  </div>
 )
}

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps((store) => async () => {
 const krwMarkets = (await getMarketSymbols()).filter(({ market }) => market.startsWith('KRW-'))
 store.dispatch(invoke(krwMarkets))

 const symbolSnake = krwMarkets
  .slice(0, 10)
  .map(({ market }) => market)
  .join(',')

 const queryClient = new QueryClient()
 await queryClient.prefetchQuery(['markets', symbolSnake], () => getMarketsTicker(symbolSnake))

 return {
  props: {
   dehydratedState: dehydrate(queryClient),
  },
 }
})

export default Home
